import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Git Record Project',
  description: 'Generated by codingjwp',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-white dark:bg-slate-500'>{children}</body>
    </html>
  )
}
