import './globals.css'
import type { Metadata } from 'next'
import Headers from '@/app/_components/Headers';

export const metadata: Metadata = {
  title: 'Git Storage File',
  description: 'Generated by codingjwp',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <Headers />
          {children}
        </div>
      </body>
    </html>
  )
}
